pluginManagement {
    repositories {
        maven { url = uri('https://maven.aliyun.com/repository/public/') }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri('https://maven.xposed.info/') }
        maven { url = uri('https://maven.aliyun.com/repository/public/') }
        maven { url = uri('https://maven.aliyun.com/repository/google/') }
        google()
        mavenCentral()
    }
}
rootProject.name = "FreeMOMO"
include ':app'
